version: '3.8'

services:
  db:
    container_name: casheer.com_db
    image: mariadb
    env_file:
      - .env.local
    environment:
      - TZ=${COMPOSE_TIMEZONE}
    volumes:
      - ./database/:/var/lib/mysql
      - ./config/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${COMPOSE_DB_PORT}:3306"
    restart: always

  wordpress:
    build:
      context: .
    container_name: casheer.com_wordpress
    depends_on:
      - db
    env_file:
      - .env.local
    environment:
      - TZ=${COMPOSE_TIMEZONE}
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    volumes:
      - ./config/docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./wordpress:/var/www/html
      - ../casheer-them:/var/www/html/wp-content/themes/casheer
    restart: always

  nginx:
    image: nginx
    container_name: casheer.com_nginx
    env_file:
      - .env.local
    ports:
      - "${COMPOSE_NGINX_PORT}:80"
    environment:
      - TZ=${COMPOSE_TIMEZONE}
    volumes:
      - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
      - ./var/log/nginx/:/var/log/nginx/
      - ../casheer-them:/var/www/html/wp-content/themes/casheer
    restart: always